[package]
authors = ["The wasm-bindgen Developers"]
edition = "2018"
name = "hello_world"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3.55"
wasm-bindgen = "0.2.74"
web-sys = {version = "0.3.55", features = ["console"]}
