name: GitHub Pages

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Git Delete unused files
      run: git rm -r --force --ignore-unmatch src Cargo.toml package.json
    - name: Git Add
      run: git add --force --verbose dist
    - name: Git Commit
      run: git commit -m "build and push to github pages" --allow-empty --verbose
    - name: Push
      run: git push origin/gh-pages
