name: GitHub Pages

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: "14"
    - name: Git Checkout
      run: git checkout -b gh-pages
    - name: Git Merge
      run: git merge --no-ff --squash --verbose -Xtheirs origin/master
    - name: Build
      run: npm run build
    - name: Git Delete unused files
      run: git rm -r --force --ignore-unmatch src Cargo.toml package.json
    - name: Git Add
      run: git add --all --verbose
    - name: Git Add dist
      run git add --force --verbose dist
    - name: Git Commit
      run: git commit -m "build and push to github pages" --allow-empty --verbose
    - name: Push
      run: git push origin/gh-pages
